---
title: "snag-trem_RFB"
author: "Jess M. Stitt"
date: "9/17/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **1. Set up the workspace**
Pre-processing and organization of materials needed to run the code, including R packages, folder & file pathways, and relevant datasets

## *1.1. Load packages for workflow organization & tidy data*
```{r library}
##--------------------------------------------------------------------------##
## Workflow organization ----
##--------------------------------------------------------------------------##
library(here)       #for file path mgmt
library(beepr)      #for [unnecessary] sound notifications
##--------------------------------------------------------------------------##
## Tidy data management ----
##--------------------------------------------------------------------------##
library(tidyverse)  #for tidy data
library(dplyr)      #for
library(tidyr)      #for
library(stringr)    #for
##--------------------------------------------------------------------------##
## Lidar analysis in R ----
##--------------------------------------------------------------------------##
library(rLiDAR)     #for lidar data manipulation & ITD**
library(lidR)     #for lidar data manipulation**
## **If not yet installed, first install with devtools
# library(devtools) #for pkg maintenance [developer tools]
# devtools::install_github("carlos-alberto-silva/rLiDAR")
# devtools::install_github("Jean-Romain/lidR")
##--------------------------------------------------------------------------##
## Spatial manipulation ----
##--------------------------------------------------------------------------##
library(raster)
library(rgdal) #for vector work
library(raster) #for metadata/attributes: vectors or rasters
library(rgeos)
library(sf)
library(sp)
##--------------------------------------------------------------------------##
## Data visualization & plotting ----
##--------------------------------------------------------------------------##
library(ggplot2)    #for plots & graphics
library(gridExtra)
library(ggpubr)     #for ggplot-based publication-ready plots & other visuals
library(ggsci)
library(hrbrthemes)
library(plotrix)    #for specialized plots
library(rstatix)
library(mapview)    #for maps
library(RColorBrewer)   #for color palettes
library(viridis)    #for addtional color palettes
##--------------------------------------------------------------------------##
## Modeling ----
##--------------------------------------------------------------------------##
library(vegan) #diversity analysis in R
library(lme4) #mixed effects modeling
library(nlme) #non-linear mixed effect modeling
library(AICcmodavg) #create model selection tables
library(sjPlot) #create model report tables

library(rsample)      # data splitting 
library(randomForest) #Random Forest modeling
# devtools::install_github("MI2DataLab/randomForestExplainer")
library(randomForestExplainer) #explainer for RF models
library(rpart)
library(party)
library(rfUtilities)
##--------------------------------------------------------------------------##
beep(1) #----
```

## *1.2. Assign project file pathways*
```{r pathways}
##--------------------------------------------------------------------------##
## INPUTS: existing datasets ----
##--------------------------------------------------------------------------##
csv <- here("01_datasets", "01_csv")    #field data files (as comma-separated)
laspc <- here("01_datasets", "02_las")  #lidar point cloud files
gis <- here("01_datasets", "03_gis")    #geospatial data files
##--------------------------------------------------------------------------##
## PROCESSING: R scripts and steps for project ----
##--------------------------------------------------------------------------##
### Code used to perform analyses
scripts <- here("02_scripts")           #R scripts
### Lidar progression
rawlas <- here(laspc,"00_las_raw_r50m")   
znf <- here(laspc,"01_las_znfil_r50m")       #znorm filtered (>0, C==1L) R50m
clipPlot <- here(laspc,"02_las_clip-plot_r25m") #lasclipCircle from znf to R25m
clipTree <- here(laspc,"03_las_clip-tree") #lasclipCircle from znf to 5x5m
clipSnag <- here(clipTree,"circular_d05m/snag-gnss") #field-derived snag PCs
clipLive <- here(clipTree, "circular_d05m/live-itd") #itd-derived live tree PCs
### Raster progression
dtm50m <- here(gis,"00_tif_dtm_r50m")
pfc <- here(gis,"01_tif_pf-chm_r50m")   #pit-free chm R50m around plots
chm50m <- here(gis,"02_asc_pf-chm_r50m")      #chm raster R50m around plots
chmPlot <- here(gis,"03_asc_chm-plot_r25m")       #chm raster from chm to R25m
shp25m <- here(gis, "04_shp_plots-clip_r25m")
##--------------------------------------------------------------------------##
## OUTPUTS: products generated during processing ----
##--------------------------------------------------------------------------##
tabs <- here("03_results", "01_tables") #results tables (as .csvs)
lasmx <- here("03_results", "02_las-metrics") #lidar-derived metrics
shp <- here("03_results", "03_gis-mod")  #shapefiles (modified)
figs <- here("03_results", "04_graphics") #graphic outputs
##--------------------------------------------------------------------------##
beep(1)  #----
##--------------------------------------------------------------------------##
```

## *1.3.Read in datasets*
```{r readr}
##--------------------------------------------------------------------------##
## Load relevant csv files ----
##--------------------------------------------------------------------------##
snagDF <- read_csv(file.path(lasmx,
                             "snag-trem_REFsnags-d05m_lasMx-allRN_full.csv"))
snagMOD <- as_tibble(snagDF) %>% 
  mutate_at(vars(site, spp, top:insects), factor) %>%
  reorder_levels(bark, c("NONE","SOME","FULL")) %>%
  reorder_levels(branches, c("N","C","M","F","V")) %>% #None,Coarse,Mid,Fine,Veg
  mutate(overcanopy = zmax - ht) %>%
  mutate(cat=cut(dbh, breaks=c(0, 0.5, 2), 
                 labels=c("small","large"))) %>%
  mutate(group = case_when(
    cat == "small" & top == "INTACT" ~ "SI",
    cat == "large" & top == "INTACT" ~ "LI",
    cat == "small" & top == "BT" ~ "SB",
    cat == "large" & top == "BT" ~ "LB"),
    .after=site) %>%
  mutate(crown = case_when(
    branches == "N" | branches == "C" ~ "NO",
    branches == "M" | branches == "F" | branches == "V" ~ "YES"),
    .after=group) %>%
  mutate_at(vars(group, crown), factor) %>% 
  reorder_levels(group, c("SI","LI","SB","LB"))

snags <- snagMOD %>%
  separate(snagid, c("plotid"), sep = "_", remove=FALSE, extra="drop") %>%
  relocate(plotid, .after = "site")
  
tidytopo <- read_csv(file.path(tabs,
                              "snag-trem_REFplots_topo-r25m.csv"))

snagRF <- full_join(snags, tidytopo, by = "plotid") %>%
  relocate(c(elev, trasp, slope), .after = "z_m") %>%
  drop_na(snagid)
glimpse(snagRF)

# Test for model collinearity
# multi.collinear(snagRF[,-c(1:8,12:22,64,65,70,71,79,80)],na.rm=TRUE) #,perm = TRUE, leave.out = TRUE, n = 999)
```

Mostly from: 
https://daviddalpiaz.github.io/r4sl/ensemble-methods.html#classification-2
```{r bagging}
library(tree)
library(rpart.plot)
library(gbm)
library(caret)
# library(iRF)

snagVars <- snagRF[,c("top","ptd","p1th", #"site","crown",
                    "GFPmid","LADcv","rumple", "ENTmid","VCI",
                    "elev","trasp","slope")] %>% #",xc","yc")] %>%
  tidyr::drop_na(); glimpse(snagVars)

calc_acc = function(actual, predicted) {
  mean(actual == predicted)}

set.seed(29)
# prop_train = list()
rfb = list()
imp = list()
prd = list()
acc = list()
prop_df = data.frame()
# rfb_df = data.frame()
# imp_df = data.frame()
# prd_df = data.frame()
acc_df = data.frame()
aK_df = data.frame()
for (i in 1:20){
  rf_split <- initial_split(snagVars, prop = 0.6)
  rf_train <- training(rf_split)
  rf_vtest <- testing(rf_split)
  prop_train <- prop.table(table(rf_train$top))
  prop_df <- rbind(prop_df, prop_train)
  print(prop.table(table(rf_train$top)))
  rfb[[i]] <- randomForest(top ~ .,
                      data = rf_train, 
                      ntree = 1000,
                      mtry = 10, 
                      importance = TRUE)
  imp[[i]] <- importance(rfb[[i]])
  prd[[i]] <- predict(rfb[[i]], newdata = rf_vtest)
  acc[[i]] <- calc_acc(predicted = prd[[i]], actual = rf_vtest$top)
  acc_df <- rbind(acc_df, acc[[i]])
  pR_aK <- postResample(prd[[i]], rf_vtest$top)
  aK_df <- rbind(aK_df, pR_aK)
}

RFnames <- as_tibble(sprintf("iter_%02d", 1:20))
colnames(prop_df)<-c("prop(BT)", "prop(INTACT)")
colnames(acc_df)<-c("model.accuracy")
colnames(aK_df)<-c("accuracy", "kappa")
iterRF <- cbind(RFnames, prop_bt=round(prop_df[,1], digits=2),
                        round(acc_df, digits=2),
                        round(aK_df, digits=3)) %>%
  arrange(desc(accuracy)); iterRF

par(mfrow=c(4,5))
for (i in 1:20) {
  iRF::varImpPlot(rfb[[i]], n.var=10, type=1,
             main=paste0('Variable Importance: ',i, ' of 20 
RF Model Accuracy = ', round(acc[[i]], digits=2)))
}
tops_best <- rfb[[05]]
importance(tops_best)
importance(tops_best)/max(abs(importance(tops_best)[,1:2]))

varImpPlot(tops_best)
iterRF %>% summarize(mean(accuracy))
summary(iterRF)

snagVars %>% 
  group_by(top) %>%
  summarize(mean(LADcv))

####
## Full RFB by GROUP ----
####
grpVars <- snagRF[,c("group","ptd","p1th", #"site","crown",
                    "GFPmid","LADcv","rumple", "ENTmid","VCI",
                    "elev","trasp","slope")] %>% #",xc","yc")] %>%
  tidyr::drop_na(); glimpse(grpVars)

set.seed(29)
# prop_train = list()
rfb_grp = list()
imp_grp = list()
prd_grp = list()
acc_grp = list()
prop_df_grp = data.frame()
# rfb_df = data.frame()
# imp_df = data.frame()
# prd_df = data.frame()
acc_grp_df = data.frame()
aK_grp_df = data.frame()
for (i in 1:20){
  rf_split_grp <- initial_split(grpVars, prop = 0.6)
  rf_train_grp <- training(rf_split)
  rf_vtest_grp <- testing(rf_split)
  prop_train_grp <- prop.table(table(rf_train$group))
  prop_grp_df <- rbind(prop_df, prop_train)
  print(prop.table(table(rf_train_grp$group)))
  rfb_grp[[i]] <- randomForest(group ~ .,
                      data = rf_train_grp, 
                      ntree = 1000,
                      mtry = 10, 
                      importance = TRUE)
  imp_grp[[i]] <- importance(rfb_grp[[i]])
  prd_grp[[i]] <- predict(rfb_grp[[i]], newdata = rf_vtest_grp)
  acc_grp[[i]] <- calc_acc(predicted = prd_grp[[i]], actual = rf_vtest_grp$group)
  acc_grp_df <- rbind(acc_grp_df, acc[[i]])
  pR_grp_aK <- postResample(prd_grp[[i]], rf_vtest_grp$group)
  aK_grp_df <- rbind(aK_grp_df, pR_grp_aK)
}

# RFnames <- as_tibble(sprintf("iter_%02d", 1:20))
colnames(prop_grp_df)<-c("prop(SI)", "prop(LI)","prop(SB)", "prop(LB)")
colnames(acc_grp_df)<-c("model.accuracy")
colnames(aK_grp_df)<-c("accuracy", "kappa")
iterRF_grp <- cbind(RFnames,round(prop_grp_df, digits=2),
                        round(acc_grp_df, digits=2),
                        round(aK_grp_df, digits=3)) %>%
  arrange(desc(accuracy)); iterRF_grp

par(mfrow=c(4,5))
for (i in 1:20) {
  iRF::varImpPlot(rfb_grp[[i]], n.var=10, type=1,
             main=paste0('Variable Importance: ',i, ' of 20 
RF Model Accuracy = ', round(acc_grp[[i]], digits=2)))
}
grps_best <- rfb[[6]]
importance(grps_best)
importance(grps_best)/max(importance(grps_best)[,1])
# importance(grps_best)/max(importance(grps_best)[,2])
varImpPlot(grps_best)
summary(iterRF)
iterRF %>% summarize(mean(accuracy))
```

``` {r gmb rfb plots}
## Set focal RF model
rfMod <- tops_best
## Make list of file names 
figList = c("1-min-depth","2-mw-imp","3-intrxns","4-pred")
## Set up RDE plots
mdf <- min_depth_distribution(rfMod)
impf <- measure_importance(rfMod)
impvars <- important_variables(impf, k = 5,
                    measures = c("mean_min_depth", "no_of_trees"))
intx <- min_depth_interactions(rfMod, impvars)
## Make plots
mindepth <- plot_min_depth_distribution(mdf)
mwImp <- plot_multi_way_importance(impf, 
                                   size_measure = "no_of_nodes")
intrxns <- plot_min_depth_interactions(intx)
mwImp
predIntrxn <- plot_predict_interaction(rfMod, snagVars, "LADcv", "p1th")
plotList = list(mindepth,mwImp,intrxns,predIntrxn)
## Save plots to png; make a separate file for each plot.
for (i in 1:4) {
  file_name = file.path(figs, paste("snag-trem_rfbTops-report_fig", 
                                      figList[[i]], ".png", sep=""))
  png(file_name,
      width = 800,
      height = 600)
  print(plotList[i])
  dev.off()
}

(tree.tops = rpart(top ~ ptd + p1th +
                         GFPmid + LADcv + rumple + 
                         elev + trasp + slope,
                       data = snagVars)); printcp(tree.tops)

# png(filename = file.path(figs,
#                           paste("snag-trem_ipnf2017-dbh_rpart-tree.png")),
#       width = 800,
#       height = 600)
# par(mfrow = c(1,2), xpd = NA) #otherwise on some devices the text is clipped
plot(tree.tops); text(tree.tops, use.n = TRUE)
par(mfrow = c(1,1))

####
## Tree Model (based on partitioning)
####
snag_part = rpart(top ~ ., data = snag_train)
rpart.plot(snag_part)
snag_part_pred = predict(snag_part, snag_vtest, type = "class")
table(predicted = snag_part_pred, actual = snag_vtest$top)
(part_acc = calc_acc(predicted = snag_part_pred, actual = snag_vtest$top))

```